### ISSUE TITLE
Crash using Vita Nex Servuo

### ISSUE THREAD

**Issue by Iomega0318** [Pack4Duck/ClassicUO#1490]
**Describe the bug**
The client crashes when scrolling through the modules list for Vita-Nex in ServUO.

**To Reproduce**
1. Go to 'Load Vita-Nex with some modules in ServUO'
2. Click on 'Try to activate the modules'
3. Scroll down 'through the module list'

######################## [START LOG] ########################
ClassicUO [STANDARD_BUILD] - 0.1.10.143 - 01/24/2022 22:57:46
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Shard: playuo.live
ClientVersion: 7.0.91.15

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.ThrowHelper.ThrowIndexOutOfRangeException()
   at ClassicUO.Network.Huffman.DecompressChunk(Span`1 src, Int32& srcOffset, Int32 srcLength, Span`1 dest, Int32 destOffset, Int32& destLength)
   at ClassicUO.Network.NetClient.DecompressBuffer(Span`1 buffer, Int32& length)
   at ClassicUO.Network.NetClient.ProcessRecv()
   at ClassicUO.Network.NetClient.Update()
   at ClassicUO.GameController.OnNetworkUpdate(Double totalTime, Double frameTime)
   at ClassicUO.GameController.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Client.Run()
   at ClassicUO.Bootstrap.Main(String[] args)

**Comment by andreakarasho** [comment]
should be fixed in latest cuo.
I close the issue in the meanwhile

**Comment by Iomega0318** [comment]
I haven't checked on this in a while and just wanted to make an update and post that this still appears to be crashing the client.
######################## [START LOG] ########################
ClassicUO [STANDARD_BUILD] - 0.1.10.255 - 06/18/2022 20:58:40
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Shard: playuo.live
ClientVersion: 7.0.91.15

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.ThrowHelper.ThrowIndexOutOfRangeException()
   at ClassicUO.Network.Huffman.DecompressChunk(Span`1 src, Int32& srcOffset, Int32 srcLength, Span`1 dest, Int32 destOffset, Int32& destLength)
   at ClassicUO.Network.NetClient.DecompressBuffer(Span`1 buffer, Int32& length)
   at ClassicUO.Network.NetClient.ProcessRecv()
   at ClassicUO.Network.NetClient.Update()
   at ClassicUO.GameController.OnNetworkUpdate()
   at ClassicUO.GameController.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at ClassicUO.Client.Run()
   at ClassicUO.Bootstrap.Main(String[] args)
######################## [END LOG] ########################
